In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个全连接层
linear = nn.Linear(3, 5)

## 常数初始化

In [4]:
nn.init.zeros_(linear.weight)
nn.init.zeros_(linear.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [5]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)


In [6]:
nn.init.ones_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [8]:
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([10., 10., 10., 10., 10.], requires_grad=True)


## 秩初始化

In [9]:
nn.init.eye_(linear.weight) # 用单位矩阵初始化权重
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)


## 随机初始化

In [10]:
# 正态分布初始化
nn.init.normal_(linear.weight, mean=0, std=1) # 用均值为0，标准差为1的正态分布初始化权重
print(linear.weight)

Parameter containing:
tensor([[-0.1372,  1.3860,  0.3265],
        [ 0.1000,  1.5371,  0.0094],
        [-0.3021, -0.7329, -2.0779],
        [ 2.9892,  0.5277,  0.6355],
        [-0.7241, -1.5124,  0.8619]], requires_grad=True)


In [11]:
nn.init.normal_(linear.weight, mean=5, std=2)
print(linear.weight)

Parameter containing:
tensor([[6.5151, 4.5962, 5.9172],
        [2.6558, 2.7112, 7.8503],
        [3.5161, 4.1627, 6.8565],
        [3.9380, 6.9820, 7.1034],
        [2.6910, 7.0268, 2.9711]], requires_grad=True)


In [12]:
# 均匀分布初始化
nn.init.uniform_(linear.weight, a=0, b=10) # 用均匀分布初始化权重，范围为[a, b)
print(linear.weight)

Parameter containing:
tensor([[0.3145, 6.5595, 6.8355],
        [4.9216, 3.3639, 0.8941],
        [9.3478, 0.0789, 3.2960],
        [5.9609, 5.0751, 4.5073],
        [1.1873, 3.9424, 2.0901]], requires_grad=True)


## Xavier初始化

In [ ]:
# Xavier初始化参数适用于Sigmoid和Tanh等激活函数，能有效缓解梯度消失或爆炸问题

In [14]:
nn.init.xavier_normal_(linear.weight) # 用Xavier正态分布初始化权重
print(linear.weight)

Parameter containing:
tensor([[ 0.1779, -0.0453,  0.1572],
        [-0.7619, -0.6961,  0.1269],
        [-0.3022,  0.7131,  0.2986],
        [ 0.5828, -0.2735, -0.5126],
        [ 0.2119,  0.3675,  0.0009]], requires_grad=True)


In [15]:
nn.init.xavier_uniform_(linear.weight) # 用Xavier均匀分布初始化权重
print(linear.weight)

Parameter containing:
tensor([[-0.2696, -0.8538, -0.8304],
        [ 0.6511,  0.5206, -0.5356],
        [ 0.3902, -0.2894,  0.1508],
        [-0.2469,  0.2100, -0.4125],
        [ 0.3278, -0.7026,  0.0306]], requires_grad=True)
