In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个全连接层
linear = nn.Linear(3, 5)

## 常数初始化

In [4]:
nn.init.zeros_(linear.weight)
nn.init.zeros_(linear.bias)

Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)

In [5]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([0., 0., 0., 0., 0.], requires_grad=True)


In [6]:
nn.init.ones_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)


In [8]:
nn.init.constant_(linear.bias, 10)
print(linear.bias)

Parameter containing:
tensor([10., 10., 10., 10., 10.], requires_grad=True)


## 秩初始化

In [9]:
nn.init.eye_(linear.weight) # 用单位矩阵初始化权重
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
