In [8]:
import torch
import torch.nn as nn
from torch import optim

# 正则化

In [3]:
x = torch.randint(0, 10, (5, 3)).float()
print(x)

tensor([[6., 2., 8.],
        [5., 5., 1.],
        [9., 7., 0.],
        [8., 6., 6.],
        [8., 1., 6.]])


## 1.Batch Normalization 批量标准化 调整各层的激活值分布使其拥有适当的广度，BN层通常放在线性层（全连接层/卷积层）之后，激活函数之前。

In [4]:
# 定义 BN 层 （Batch Normalization 批量标准化）
bn = nn.BatchNorm1d(3)

In [5]:
y = bn(x)
print(y)

tensor([[-0.8165, -0.9503,  1.2163],
        [-1.4969,  0.3455, -1.0243],
        [ 1.2247,  1.2094, -1.3444],
        [ 0.5443,  0.7775,  0.5762],
        [ 0.5443, -1.3822,  0.5762]], grad_fn=<NativeBatchNormBackward0>)


## 2. 权值衰减 通过在学习的过程中对大的权重进行“惩罚”，可以有效的抑制过拟合

In [10]:
model = nn.Linear(1, 3)
optimizer = optim.SGD(model.parameters(), lr=0.1, weight_decay=1e-2) # weight_decay: 正则化系数

## 3. Dropout 随机失活（暂退法） 在训练过程中随机的将一部分神经元的输出置为0（关闭神经元），防止神经元之间过度依赖，通常放在激活函数之后，下一个线性层（全连接层/卷积层）之前

In [14]:
x = torch.randint(1, 10, (10, )).float()
print(x)

tensor([3., 7., 9., 9., 3., 9., 3., 4., 4., 6.])


In [15]:
# 定义 Dropout 层
dropout = nn.Dropout(p=0.5) # p: 失活概率 每个神经元以0.5的概率关闭

In [17]:
y = dropout(x)
print(y) # 没关闭的神经元，会进行缩放，按 1/(1-p) = 1(1-0.5) = 2 的比例放大

tensor([ 6., 14., 18.,  0.,  0., 18.,  0.,  0.,  0.,  0.])
