In [2]:
import torch
import torch.nn as nn

In [3]:
# 定义一个线性层，输入特征数为2，输出特征数为3 (定义了一个有2个输入神经元、3个输出神经元的全连接层)
linear = nn.Linear(in_features=2, out_features=3)

In [4]:
print("权重：", linear.weight) # [[w11, w21], [w12, w22], [w13, w23]].T

权重： Parameter containing:
tensor([[-0.2478, -0.1507],
        [ 0.1410, -0.6303],
        [-0.5927, -0.1408]], requires_grad=True)


In [5]:
print("偏置：", linear.bias) # b1 b2 b3

偏置： Parameter containing:
tensor([-0.6671,  0.3346, -0.5708], requires_grad=True)


## 前向传播

In [6]:
import torch

# 输入数据
x = torch.Tensor([1, 2]) # 输入特征数为2

In [7]:
# 前向传播，得到输出
y = linear.forward(x)
print(y) # y1 = w11*x1 + w21*x2 + b1, y2 = w12*x1 + w22*x2 + b2, y3 = w13*x1 + w23*x2 + b3

tensor([-1.2162, -0.7850, -1.4450], grad_fn=<ViewBackward0>)


In [8]:
# 输入多条数据
X = torch.randn(5, 2) # 5条数据，每条数据有2个特征

In [9]:
y = linear.forward(X) # 输入5条数据，得到5条输出，每条输出有3个特征 5x3
print(y)

tensor([[-0.4137,  0.5739, -0.0824],
        [-0.4534,  0.2073, -0.0579],
        [-0.4566,  1.2210, -0.3758],
        [-0.5773,  1.4747, -0.7214],
        [-1.1578,  0.3665, -1.6687]], grad_fn=<AddmmBackward0>)


In [10]:
# 输入高维数据
X = torch.randn(10, 5, 2) # 10个样本，每个样本有5条数据，每条数据有2个特征 10x5x2

In [11]:
y = linear.forward(X) # 输入10个样本，每个样本有5条数据，每条数据有2个特征，得到10个样本，每个样本有 10x5x3
print(y)

tensor([[[-0.7304,  0.4055, -0.7329],
         [-1.0414, -0.0141, -1.2938],
         [-1.1381,  0.9775, -1.8122],
         [-0.7729,  0.2412, -0.7767],
         [-1.0608, -0.2619, -1.2608]],

        [[-0.2078, -0.9429,  0.8395],
         [-0.7057, -0.2121, -0.4887],
         [ 0.1244,  1.8888,  0.7075],
         [-0.8922,  0.4808, -1.1148],
         [-0.9971,  0.0474, -1.2144]],

        [[-0.6128,  0.6314, -0.5413],
         [-0.5866, -0.1656, -0.2389],
         [-0.7948,  0.6326, -0.9453],
         [-0.4239,  1.2263, -0.3050],
         [-0.9598,  0.6976, -1.3311]],

        [[-0.2442,  0.3705,  0.3560],
         [-1.3373, -0.2202, -1.8867],
         [-0.6230, -0.3179, -0.2729],
         [-0.9761,  0.4593, -1.2942],
         [-0.3837,  1.7057, -0.3629]],

        [[-0.5416,  0.0276, -0.1984],
         [-0.6721,  0.1919, -0.5382],
         [-0.5115,  0.5016, -0.2769],
         [-1.3176,  0.2993, -2.0023],
         [-0.7421, -0.1222, -0.5970]],

        [[-0.6564,  0.4308, -0.5766],
  

In [12]:
y = linear(X) # 与调用forward方法等价
print(y.shape)

torch.Size([10, 5, 3])


In [13]:
linear2 = nn.Linear(in_features=3, out_features=5) # 定义一个线性层，输入特征数为3，输出特征数为5

In [14]:
z = linear2.forward(y) # y 是linear1输出的10个样本，每个样本5条数据，每条数据3个特征（10x5x3），作为linear2的输入，得到10个样本，每个样本5条数据，每条数据5个特征（10x5x5）
print(z.shape)

torch.Size([10, 5, 5])


## 设备测试

In [17]:
# input = torch.tensor([1, 2, 3], dtype=torch.float32, device="cuda") # 将输入数据放到GPU上
input = torch.tensor([1, 2, 3], dtype=torch.float32)

In [18]:
print(input.device)

cpu


In [20]:
input = input.to("cuda") # 将输入数据放到GPU上
print(input.device)

cuda:0
