In [1]:
import torch
import torch.nn as nn

In [2]:
# 定义一个线性层，输入特征数为2，输出特征数为3 (定义了一个有2个输入神经元、3个输出神经元的全连接层)
linear = nn.Linear(in_features=2, out_features=3)

In [3]:
print("权重：", linear.weight) # [[w11, w21], [w12, w22], [w13, w23]].T

权重： Parameter containing:
tensor([[-0.2109, -0.4971],
        [ 0.0187,  0.5574],
        [-0.0408,  0.5061]], requires_grad=True)


In [4]:
print("偏置：", linear.bias) # b1 b2 b3

偏置： Parameter containing:
tensor([-0.3878, -0.2306,  0.4614], requires_grad=True)


## 前向传播

In [8]:
import torch

# 输入数据
x = torch.Tensor([1, 2]) # 输入特征数为2

In [11]:
# 前向传播，得到输出
y = linear.forward(x)
print(y) # y1 = w11*x1 + w21*x2 + b1, y2 = w12*x1 + w22*x2 + b2, y3 = w13*x1 + w23*x2 + b3

tensor([-1.5929,  0.9029,  1.4327], grad_fn=<ViewBackward0>)


In [12]:
# 输入多条数据
X = torch.randn(5, 2) # 5条数据，每条数据有2个特征

In [14]:
y = linear.forward(X) # 输入5条数据，得到5条输出，每条输出有3个特征 5x3
print(y)

tensor([[-1.3053,  0.8777,  1.4887],
        [ 0.1143, -0.7641, -0.0152],
        [-0.4330, -0.0871,  0.6163],
        [-1.0024,  0.3347,  0.9418],
        [ 0.1270, -0.9442, -0.2227]], grad_fn=<AddmmBackward0>)


In [16]:
# 输入高维数据
X = torch.randn(10, 5, 2) # 10个样本，每个样本有5条数据，每条数据有2个特征 10x5x2

In [19]:
y = linear.forward(X) # 输入10个样本，每个样本有5条数据，每条数据有2个特征，得到10个样本，每个样本有 10x5x3
print(y)

tensor([[[ 1.8652e-02, -5.0426e-01,  2.6120e-01],
         [ 2.4751e-01, -7.6380e-01,  2.4789e-02],
         [-1.1925e+00,  5.8412e-01,  1.1778e+00],
         [-1.4651e-01, -6.3654e-01,  5.6873e-02],
         [ 1.6952e-01, -9.6828e-01, -2.3832e-01]],

        [[-3.1373e-01, -1.6206e-01,  5.6380e-01],
         [-3.9979e-01,  3.5553e-04,  7.2875e-01],
         [ 2.6518e-01, -1.0671e+00, -3.2579e-01],
         [-9.5990e-01,  3.4981e-02,  6.0275e-01],
         [-1.1626e-01, -1.6249e-01,  6.2203e-01]],

        [[-2.4626e-01, -4.0123e-01,  3.0327e-01],
         [-4.3040e-01, -5.4136e-01,  8.4097e-02],
         [ 4.5540e-01, -9.6393e-01, -1.4816e-01],
         [-7.2165e-01, -1.2919e-01,  4.8102e-01],
         [-7.8635e-01,  2.2714e-01,  8.7982e-01]],

        [[-9.8343e-01,  2.8461e-01,  8.8861e-01],
         [ 3.6618e-02, -5.0710e-01,  2.6322e-01],
         [-1.6118e+00,  9.3110e-01,  1.4602e+00],
         [-5.0742e-01, -3.9563e-01,  2.3215e-01],
         [-1.4484e+00,  9.4361e-01,  1.5234e

In [20]:
y = linear(X) # 与调用forward方法等价
print(y.shape)

torch.Size([10, 5, 3])
