In [1]:
import torch

In [ ]:
x = torch.tensor([0.7, -1.2, 2.5, 0, -3.1])

## 阶跃函数 （现代神经网络，训练时几乎不用阶跃函数作为激活函数）

In [5]:
print(torch.sign(x)) # torch.sign(x) 返回一个张量，表示输入张量 x 中每个元素的符号，正数为1，负数为-1，0为0。

tensor([ 1., -1.,  1.,  0., -1.])


In [8]:
print(torch.signbit(x)) # torch.signbit(x) 返回一个布尔张量，表示输入张量 x 中每个元素的符号位，正数为False，负数为True，0为False。
print(torch.signbit(-x).long())

tensor([False,  True, False, False,  True])
tensor([1, 0, 1, 1, 0])
