In [12]:
import torch
import torch.nn as nn

In [ ]:
x = torch.tensor([0.7, -1.2, 2.5, 0, -3.1])

## 阶跃函数 （现代神经网络，训练时几乎不用阶跃函数作为激活函数）

In [5]:
print(torch.sign(x)) # torch.sign(x) 返回一个张量，表示输入张量 x 中每个元素的符号，正数为1，负数为-1，0为0。

tensor([ 1., -1.,  1.,  0., -1.])


In [8]:
print(torch.signbit(x)) # torch.signbit(x) 返回一个布尔张量，表示输入张量 x 中每个元素的符号位，正数为False，负数为True，0为False。
print(torch.signbit(-x).long())

tensor([False,  True, False, False,  True])
tensor([1, 0, 1, 1, 0])


## Sigmoid函数

In [10]:
# 使用Sigmoid函数作为激活函数，由于Sigmoid函数会出现梯度丢，所以在神经网络中常用于二分类的输出层，很少用于中间层
print(torch.sigmoid(x))

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [11]:
y = x.sigmoid()
print(y)

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [13]:
# 使用nn 下的类
sig = nn.Sigmoid()
print(sig(x))

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


# Tanh函数 (双曲正切函数)

In [18]:
# 常用在中间层（隐藏层），不能能用于二分类输出层
print(torch.tanh(x))
print(x.tanh())
tanh = nn.Tanh()
print(tanh(x))

tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
