In [2]:
import torch
import torch.nn as nn

In [3]:
x = torch.tensor([0.7, -1.2, 2.5, 0, -3.1])

## 阶跃函数 （现代神经网络，训练时几乎不用阶跃函数作为激活函数）

In [4]:
print(torch.sign(x)) # torch.sign(x) 返回一个张量，表示输入张量 x 中每个元素的符号，正数为1，负数为-1，0为0。

tensor([ 1., -1.,  1.,  0., -1.])


In [5]:
print(torch.signbit(x)) # torch.signbit(x) 返回一个布尔张量，表示输入张量 x 中每个元素的符号位，正数为False，负数为True，0为False。
print(torch.signbit(-x).long())

tensor([False,  True, False, False,  True])
tensor([1, 0, 1, 1, 0])


## Sigmoid函数

In [6]:
# 使用Sigmoid函数作为激活函数，由于Sigmoid函数会出现梯度丢失，所以在神经网络中常用于二分类的输出层，很少用于中间层
print(torch.sigmoid(x))

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [7]:
y = x.sigmoid()
print(y)

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


In [8]:
# 使用nn 下的类
sig = nn.Sigmoid()
print(sig(x))

tensor([0.6682, 0.2315, 0.9241, 0.5000, 0.0431])


# Tanh函数 (双曲正切函数)

In [9]:
# 常用在中间层（隐藏层），不能能用于二分类输出层
print(torch.tanh(x))
print(x.tanh())
tanh = nn.Tanh()
print(tanh(x))

tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])
tensor([ 0.6044, -0.8337,  0.9866,  0.0000, -0.9959])


## ReLU函数（修正线性单元）

In [10]:
# 常用于隐藏层 会将小于0的输入转换为0，大于等于0的输入则保持不变，ReLU函数在训练深度神经网络时表现良好，且计算简单
print(torch.relu(x))
print(x.relu())
relu = nn.ReLU()
print(relu(x))

tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])
tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])
tensor([0.7000, 0.0000, 2.5000, 0.0000, 0.0000])


## Softmax函数

In [13]:
# 常用于多分类输出层，将一个任意的实数向量转换为一个概率分布，确保输出值的总和为1.
print(torch.softmax(x, dim=0))
print(x.softmax(dim=0))
softmax = nn.Softmax(dim=0)
print(softmax(x))

tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])
tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])
tensor([0.1296, 0.0194, 0.7838, 0.0643, 0.0029])


In [14]:
X = torch.randn(3, 2)
print(X)

tensor([[-0.2361,  0.0554],
        [-0.1572,  0.5198],
        [-0.0431,  1.2704]])


In [15]:
print(torch.softmax(X, dim=1)) # X是一个3行2列的张量，dim=1表示对每一行进行softmax操作，即对每一行的元素进行归一化，使得每一行的元素之和为1。

tensor([[0.4276, 0.5724],
        [0.3369, 0.6631],
        [0.2119, 0.7881]])
