In [12]:
import torch

## detach 对张量的影响

In [13]:
# 定义数据
x = torch.tensor(2.0, requires_grad=True)
print(x)

tensor(2., requires_grad=True)


In [14]:
y = x.detach()
print(y)

tensor(2.)


In [15]:
print(x.requires_grad)
print(y.requires_grad)

True
False


In [17]:
print(x.untyped_storage().data_ptr())
print(y.untyped_storage().data_ptr())

5434631680
5434631680


In [18]:
# 分别基于新，y进行计算
z1 = x ** 2
z2 = y ** 2

In [19]:
print(z1)
print(z2)

tensor(4., grad_fn=<PowBackward0>)
tensor(4.)


In [20]:
z1.backward()

In [21]:
z2.backward() # 会报错，因为y不需要梯度

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

## detach后参与计算的影响

In [28]:
# 定义输入数据
x = torch.ones(2, 2, requires_grad=True)

In [29]:
# 定义后续运算
y = x ** 2
print(y)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<PowBackward0>)


In [36]:
# 分离
u = y.detach() + torch.ones_like(y)
print(u)

tensor([[2., 2.],
        [2., 2.]])


In [32]:
# 让u与x进行计算，得到输出
z = u * x
print(z)

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


In [34]:
# 反向传播
z.sum().backward()

In [35]:
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [39]:
# 让y与x进行计算，得到输出
x1 = y * x
print(z2)

tensor(4.)
