In [26]:
import torch
from torch.utils.data import Dataset, TensorDataset, DataLoader

In [27]:
# 自定义数据集类
class MyDataset(Dataset):
    # 初始化
    def __init__(self, data):
        self.data = data

    # 返回数据集的大小
    def __len__(self):
        return len(self.data)

    # 返回指定索引的数据
    def __getitem__(self, idx):
        return self.data[idx]

In [28]:
# 利用数据列表创建数据集
data = [1, 2, 3, 4, 5]
dataset = MyDataset(data)

In [29]:
print(dataset[1])

2


## TensorDataset

In [30]:
X = torch.randn(2, 3)
y = torch.tensor([1, 0])
print(X)
print(y)

tensor([[-0.1621,  0.8622,  2.3952],
        [ 0.4887,  0.6924,  1.6691]])
tensor([1, 0])


In [31]:
# 构建数据集
dataset = TensorDataset(X, y)

In [32]:
print(dataset[1])

(tensor([0.4887, 0.6924, 1.6691]), tensor(0))
