In [1]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [2]:
# 定义数据
X = torch.randn(10, 3) # 10个样本，每个样本3个特征
y = torch.randn(10) # 10个样本的标签
print(X)
print(y)

tensor([[ 0.8326,  0.1195,  1.8039],
        [ 0.2171,  0.9322,  0.1277],
        [-1.1430,  1.0188, -1.2026],
        [-0.0580,  0.4633,  0.8253],
        [-0.7013,  0.1832,  0.1729],
        [-0.2060, -0.0271, -0.7304],
        [ 1.4362, -0.5120, -0.6832],
        [ 0.5408, -1.3079,  0.0681],
        [ 2.1749,  0.4037,  0.6109],
        [ 0.3255,  0.5240,  0.1065]])
tensor([ 1.4908, -0.6137,  0.8621,  0.4890, -0.4238, -0.9761,  0.3134,  0.3871,
        -0.1507, -0.0267])


In [3]:
# 定义数据集
dataset = TensorDataset(X, y)

In [4]:
print(dataset[2]) # 从X和y中取出索引为2的样本

(tensor([-1.1430,  1.0188, -1.2026]), tensor(0.8621))


In [14]:
# 创建数据加载器
# batch_size: 每个批次的样本数
# shuffle: 是否打乱数据
# drop_last: 如果数据集大小不能被batch_size整除，是否丢弃
dataloader = DataLoader(dataset=dataset, batch_size=4, shuffle=True, drop_last=True)

In [15]:
# 遍历数据
for x_batch, y_batch in dataloader:
    print(x_batch)
    print(y_batch)
    print('---')

tensor([[ 1.4362, -0.5120, -0.6832],
        [-1.1430,  1.0188, -1.2026],
        [ 2.1749,  0.4037,  0.6109],
        [ 0.3255,  0.5240,  0.1065]])
tensor([ 0.3134,  0.8621, -0.1507, -0.0267])
---
tensor([[-0.2060, -0.0271, -0.7304],
        [ 0.2171,  0.9322,  0.1277],
        [-0.7013,  0.1832,  0.1729],
        [-0.0580,  0.4633,  0.8253]])
tensor([-0.9761, -0.6137, -0.4238,  0.4890])
---
