In [30]:
import torch
from torch import nn, optim # optim：优化器

In [31]:
# 自定义模型
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        # 全连接层
        self.linear = nn.Linear(5, 3) # 输入特征数为5，输出特征数为3
        # 初始化权重
        self.linear.weight.data = torch.tensor(
            [
                [0.1, 0.2, 0.3],
                [0.4, 0.5, 0.6],
                [0.7, 0.8, 0.9],
                [1.0, 1.1, 1.2],
                [1.3, 1.4, 1.5],
            ]
        ).T
        # 初始化偏置
        self.linear.bias.data = torch.tensor([1.0, 2.0, 3.0])

    # 前向传播
    def forward(self, x):
        y = self.linear(x)
        return y

In [32]:
# 1. 定义数据
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
# 目标值，三分类独热编码后的分类标签
target = torch.tensor([0, 0, 1]).float()

In [33]:
# 2. 定义模型
model = MyModel()
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[0.1000, 0.4000, 0.7000, 1.0000, 1.3000],
        [0.2000, 0.5000, 0.8000, 1.1000, 1.4000],
        [0.3000, 0.6000, 0.9000, 1.2000, 1.5000]], requires_grad=True)
Parameter containing:
tensor([1., 2., 3.], requires_grad=True)


In [59]:
# 3. 训练模型
# 3.1 前向传播， 计算输出值
output = model(x)
print("输出值: ", output)

输出值:  tensor([-296.1051, -347.1577, -376.7893], grad_fn=<ViewBackward0>)


In [60]:
# 3.2 计算损失
loss_fn = nn.MSELoss()
loss = loss_fn(output, target)
print("损失值: ", loss)

损失值:  tensor(116973.8359, grad_fn=<MseLossBackward0>)


In [61]:
# 3.3 反向传播，计算梯度
loss.backward()

In [62]:
print(model.linear.weight.grad)
print(model.linear.bias.grad)

tensor([[ -197.4034,  -394.8068,  -592.2102,  -789.6136,  -987.0171],
        [ -231.4385,  -462.8770,  -694.3154,  -925.7539, -1157.1924],
        [ -251.8595,  -503.7191,  -755.5786, -1007.4382, -1259.2977]])
tensor([-197.4034, -231.4385, -251.8595])


In [63]:
E = 2 / 3 * (output - target).reshape(1, -1) # reshape(1, -1) 将输出值和目标值的差值转换为二维张量
X = x.reshape(1, -1)
grad_W = X.T @ E # 梯度计算公式：grad_W = X.T @ E
print("权重梯度: ", grad_W)

权重梯度:  tensor([[ -197.4034,  -231.4385,  -251.8595],
        [ -394.8068,  -462.8770,  -503.7191],
        [ -592.2102,  -694.3154,  -755.5786],
        [ -789.6136,  -925.7539, -1007.4382],
        [ -987.0171, -1157.1924, -1259.2977]], grad_fn=<MmBackward0>)


In [64]:
# 3.4 更新参数（迭代1次）
optimizer = optim.SGD(model.parameters(), lr=0.1) # 定义优化器，使用随机梯度下降法
optimizer.step()


In [65]:
print("更新后的权重: ", model.linear.weight)

更新后的权重:  Parameter containing:
tensor([[14.2938, 28.7876, 43.2815, 57.7753, 72.2691],
        [16.8410, 33.7821, 50.7231, 67.6641, 84.6052],
        [18.4094, 36.8187, 55.2281, 73.6374, 92.0468]], requires_grad=True)


In [57]:
# 3.5 梯度清零
optimizer.zero_grad()

In [58]:
print(model.linear.weight.grad)

None
