# 张量创建

In [76]:
import numpy as np
import torch

# 基本张量创建

## 1. 基于内容创建张量

In [22]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [23]:
print(tensor1.shape)

torch.Size([])


In [24]:
# 传入一个列表
tensor2 = torch.tensor([1, 2, 3, 4, 5])
print(tensor2)
print(tensor2.shape)

tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [25]:
# 传入二维列表（矩阵）
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [26]:
# 传入高维列表
tensor4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[70, 80, 90], [100, 110, 120]]])
print(tensor4)
print(tensor4.shape) # torch.Size([2, 2, 3]) 表示张量由2个矩阵，每个矩阵有2行3列组成

tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 70,  80,  90],
         [100, 110, 120]]])
torch.Size([2, 2, 3])


In [27]:
print(tensor4.dtype)

torch.int64


In [28]:
# 传入数据类型为浮点型
tensor5 = torch.tensor([1, 2, 3.0])
print(tensor5)
print(tensor5.dtype)

tensor([1., 2., 3.])
torch.float32


In [29]:
# 传入一个ndarray
tensor6 = torch.tensor(np.array([1, 2, 3.0]))
print(tensor6)
print(tensor6.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


## 2. 基于形状创建张量

In [30]:
tensor1 = torch.Tensor(3, 2, 4) # 创建一个3维张量，形状为(3, 2, 4)，即3个矩阵，每个矩阵有2行4列组成
print(tensor1)
print(tensor1.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 2, 4])


In [31]:
tensor2 = torch.Tensor(10) # 创建一个1维张量，形状为(10,)，即10个元素组成
print(tensor2)
print(tensor2.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])


In [32]:
print(tensor2.dtype)

torch.float32


In [33]:
# 也可以指定内容创建张量
tensor3 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [34]:
print(tensor3.dtype)

torch.float32


## 3. 创建指定数据类型的张量

In [35]:
# 整数类型
# 1. int32
tensor1 = torch.tensor([1, 2, 3], dtype=torch.int32)
print(tensor1)
print(tensor1.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [37]:
tensor2 = torch.IntTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([[ 738462528,       1128, 1077936128],
        [1082130432, 1084227584, 1086324736]], dtype=torch.int32)
torch.int32


In [43]:
# 2. int64
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.int64)
print(tensor1)
print(tensor1.dtype)

tensor([1, 2, 3])
torch.int64


In [45]:
tensor2 = torch.LongTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([[1, 1, 1],
        [1, 1, 1]])
torch.int64


In [47]:
# 3. int16
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.int16)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.ShortTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([1, 2, 3], dtype=torch.int16)
torch.int16
tensor([[    0, 16512,     0],
        [16384,     0, 16448]], dtype=torch.int16)
torch.int16


In [51]:
# 3. int8
# int8: 有符号的8位整数，取值范围为[-128, 127]，对应的torch数据类型为torch.int8
# uint8: 无符号的8位整数，取值范围为[0, 255]，对应的torch数据类型为torch.uint8
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.uint8)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.ByteTensor(2, 3) # 创建一个2行3列的整型张量 默认是uint8
print(tensor2)
print(tensor2.dtype)

tensor([1, 2, 3], dtype=torch.uint8)
torch.uint8
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.uint8)
torch.uint8


In [54]:
# 浮点数
# 1. 单精度
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.float32) # 默认是float32
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.FloatTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([1.2000, 2.9000, 3.0000])
torch.float32
tensor([[1.8765e-12, 1.5807e-42, 2.0000e+00],
        [2.1125e+00, 0.0000e+00, 2.1250e+00]])
torch.float32


In [57]:
# 2. 双精度
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.float64)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.DoubleTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([1.2000, 2.9000, 3.0000], dtype=torch.float64)
torch.float64
tensor([[4.9407e-324, 4.9407e-324, 4.9407e-324],
        [4.9407e-324, 4.9407e-324, 4.9407e-324]], dtype=torch.float64)
torch.float64


In [59]:
# 3. 半精度
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.float16)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.HalfTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([1.2002, 2.9004, 3.0000], dtype=torch.float16)
torch.float16
tensor([[1.9646e-04, 6.2561e-02, 6.7234e-05],
        [0.0000e+00, 0.0000e+00, 2.1250e+00]], dtype=torch.float16)
torch.float16


In [75]:
# 布尔类型
tensor1 = torch.tensor([1.2, 2.9, 3], dtype=torch.bool)
print(tensor1)
print(tensor1.dtype)
tensor2 = torch.BoolTensor(2, 3) # 创建一个2行3列的整型张量
print(tensor2)
print(tensor2.dtype)

tensor([True, True, True])
torch.bool
tensor([[False, False, False],
        [False, False, False]])
torch.bool


# 指定区间创建张量

In [78]:
# 1. arange
tensor1 = torch.arange(10) # 创建一个一维张量，包含从0到10（不包括10）的整数，步长为1
print(tensor1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [100]:
tensor2 = torch.arange(start=10, end=30, step=2) # 创建一个一维张量，包含从10到30（不包括30）的整数，步长为2
print(tensor2)
print(tensor2.dtype)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])
torch.int64


In [87]:
# 2. linspace
tensor1 = torch.linspace(start=10, end=30, steps=5) # 创建一个一维张量，包含从10到30（包括30）的5个等间距的数 step(步长)=(end - start) / (steps - 1) = (30 - 10) / (5 - 1) = 20 / 4 = 5
print(tensor1)

tensor([10., 15., 20., 25., 30.])


In [101]:
# 3. logspace
tensor1 = torch.linspace(start=1, end=3, steps=3)
tensor2 = torch.logspace(start=1, end=3, steps=3, base=2) # 在区间[start, end]之间生成steps个数，并以 base 为底，区间内数为指数创建张量。先计算出linspace 的值，然后以 base 为底，计算出对应的指数值。即 tensor2 = base ** tensor1
print(tensor1)
print(tensor2)

tensor([1., 2., 3.])
tensor([2., 4., 8.])


# 按数值填充张量

In [114]:
# 1. 创建指定形状的全0张量
tensor1 = torch.zeros(size=(2,3), dtype=torch.float64)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [116]:
# 2. 创建指定形状的全1张量
tensor1 = torch.ones(size=(2,3), dtype=torch.int32)
print(tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [117]:
# 3. 创建指定形状的按指定值填充的张量
tensor1 = torch.full(size=(2,3), fill_value=5, dtype=torch.int64)
print(tensor1)

tensor([[5, 5, 5],
        [5, 5, 5]])


In [120]:
# 4. 创建指定形状的未初始化的张量
tensor1 = torch.empty(size=(2, 3), dtype=torch.float32)
print(tensor1)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [122]:
# 5. 创建与给定张量形状相同的全0张量
tensor_ = torch.full(size=(2, 3), fill_value=5, dtype=torch.int64)
tensor1 = torch.zeros_like(tensor_)
print(tensor1)
print(tensor1)

tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[0, 0, 0],
        [0, 0, 0]])


In [124]:
# 6. 创建与给定张量形状相同的全1张量
tensor1 = torch.ones_like(tensor_)
print(tensor1)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [125]:
# 7. 创建与给定张量形状相同的按指定值填充的张量
tensor1 = torch.full_like(tensor_, 10)
print(tensor1)

tensor([[10, 10, 10],
        [10, 10, 10]])


In [126]:
# 8. 创建与给定张量形状相同的未初始化的张量
tensor1 = torch.empty_like(tensor_)
print(tensor1)

tensor([[0, 0, 0],
        [0, 0, 0]])


In [128]:
# 创建单位矩阵
tensor3 = torch.eye(3) # 创建3阶单位矩阵
print(tensor3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [131]:
tensor4 = torch.eye(3, 5) # 创建3行5列的单位矩阵，单位矩阵是一个方阵，主对角线上的元素为1，其余元素为0。torch.eye(n, m) 创建一个n行m列的单位矩阵，如果n != m，则创建一个非方阵的单位矩阵。
print(tensor4)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])


# 随机张量创建

In [133]:
# 1. 创建[0, 1)上均匀分布的，指定形状的张量
tensor1 = torch.rand(size=(2, 3))
print(tensor1)

tensor([[0.7236, 0.9611, 0.6634],
        [0.4690, 0.4493, 0.7079]])


In [137]:
# 2. 创建在[low, high)上均匀分布的，指定形状的张量
tensor1 = torch.randint(low=2, high=5, size=(2, 3))
print(tensor1)

tensor([[4, 3, 2],
        [3, 3, 3]])


In [140]:
# 3. 创建标准正态分布的，指定形状的张量
tensor1 = torch.randn(size=(4, 2))
print(tensor1)

tensor([[ 0.2164,  0.9808],
        [ 0.8413,  1.1814],
        [ 0.2302, -0.6840],
        [ 1.0714, -1.1913]])


In [163]:
# 4. 创建自定义正态分布的，指定形状的张量
tensor1 = torch.normal(mean=0, std=1, size=tensor1.shape) # mean: 均值，std: 标准差
print(tensor1)

tensor([[-0.8112, -1.5406, -1.0563],
        [ 0.2717, -0.3568,  0.0774]])


In [155]:
# 5. 创建[0, 1)上均匀分布的，与给定张量形状相同的张量
tensor_ = torch.full(size=(2, 3), fill_value=3.0)
tensor1 = torch.rand_like(tensor_)
print(tensor_)
print(tensor1)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[0.5168, 0.6517, 0.8957],
        [0.2570, 0.7584, 0.8868]])


In [160]:
# 6. 创建[low, high)上均匀分布的，与给定张量形状相同的张量
tensor1 = torch.randint_like(tensor_, low=2, high=5)
print(tensor1)

tensor([[3., 2., 2.],
        [4., 4., 2.]])


In [157]:
# 7. 创建标准正态分布的，与给定张量形状相同的张量
tensor1 = torch.randn_like(tensor_)
print(tensor1)

tensor([[-1.0920, -0.0730,  0.4522],
        [-0.4575, -0.7905, -0.3268]])


In [169]:
# 生成从0到n-1的随机序列，类似洗牌
tensor1 = torch.randperm(10) # 生成一个从0到9的随机序列，类似洗牌
print(tensor1)

tensor([0, 9, 8, 1, 3, 4, 5, 7, 6, 2])


In [171]:
# 查看随机数种子
print(torch.random.initial_seed())

15675847685215139633


In [172]:
# 设置随机数种子
torch.manual_seed(42) # 设置随机数种子为42
print(torch.random.initial_seed())

42
