# 张量创建

In [1]:
import numpy as np
import torch

## 1. 基于内容创建张量

In [3]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [5]:
print(tensor1.shape)

torch.Size([])


In [7]:
# 传入一个列表
tensor2 = torch.tensor([1, 2, 3, 4, 5])
print(tensor2)
print(tensor2.shape)

tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [9]:
# 传入二维列表（矩阵）
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [13]:
# 传入高维列表
tensor4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[70, 80, 90], [100, 110, 120]]])
print(tensor4)
print(tensor4.shape) # torch.Size([2, 2, 3]) 表示张量由2个矩阵，每个矩阵有2行3列组成

tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 70,  80,  90],
         [100, 110, 120]]])
torch.Size([2, 2, 3])


In [14]:
print(tensor4.dtype)

torch.int64


In [15]:
# 传入数据类型为浮点型
tensor5 = torch.tensor([1, 2, 3.0])
print(tensor5)
print(tensor5.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
# 传入一个ndarray
tensor6 = torch.tensor(np.array([1, 2, 3.0]))
print(tensor6)
print(tensor6.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
