# 张量创建

In [59]:
import numpy as np
import torch

## 1. 基于内容创建张量

In [60]:
# 传入一个标量
tensor1 = torch.tensor(10)
print(tensor1)

tensor(10)


In [61]:
print(tensor1.shape)

torch.Size([])


In [62]:
# 传入一个列表
tensor2 = torch.tensor([1, 2, 3, 4, 5])
print(tensor2)
print(tensor2.shape)

tensor([1, 2, 3, 4, 5])
torch.Size([5])


In [63]:
# 传入二维列表（矩阵）
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [64]:
# 传入高维列表
tensor4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[70, 80, 90], [100, 110, 120]]])
print(tensor4)
print(tensor4.shape) # torch.Size([2, 2, 3]) 表示张量由2个矩阵，每个矩阵有2行3列组成

tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[ 70,  80,  90],
         [100, 110, 120]]])
torch.Size([2, 2, 3])


In [65]:
print(tensor4.dtype)

torch.int64


In [66]:
# 传入数据类型为浮点型
tensor5 = torch.tensor([1, 2, 3.0])
print(tensor5)
print(tensor5.dtype)

tensor([1., 2., 3.])
torch.float32


In [67]:
# 传入一个ndarray
tensor6 = torch.tensor(np.array([1, 2, 3.0]))
print(tensor6)
print(tensor6.dtype)

tensor([1., 2., 3.], dtype=torch.float64)
torch.float64


## 2. 基于形状创建张量

In [68]:
tensor1 = torch.Tensor(3, 2, 4) # 创建一个3维张量，形状为(3, 2, 4)，即3个矩阵，每个矩阵有2行4列组成
print(tensor1)
print(tensor1.shape)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([3, 2, 4])


In [69]:
tensor2 = torch.Tensor(10) # 创建一个1维张量，形状为(10,)，即10个元素组成
print(tensor2)
print(tensor2.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.Size([10])


In [70]:
print(tensor2.dtype)

torch.float32


In [71]:
# 也可以指定内容创建张量
tensor3 = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor3)
print(tensor3.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [73]:
print(tensor3.dtype)

torch.float32
