In [1]:
import torch
import numpy as np

# 张量转换

## 元素类型转换

In [5]:
tensor1 = torch.tensor([1, 2, 3])
print(tensor1.dtype)

torch.int64


In [7]:
# type 方法
tensor1 = tensor1.type(torch.float32)
print(tensor1.dtype)

torch.float32


In [12]:
# 直接调用类型方法
tensor1 = tensor1.double() # 转换为 double 类型
print(tensor1.dtype)

torch.float64


In [13]:
# to方法
tensor1 = tensor1.to(torch.int64)
print(tensor1.dtype)

torch.int64


## Tensor 与 ndarray 转换

In [19]:
np.set_printoptions(precision=6) # 设置打印精度为6位小数
torch.set_printoptions(precision=6) # 设置打印精度为6位小数

In [20]:
# 1. Tensor 转 ndarray
tensor1 = torch.rand(3, 2) # 创建一个3行2列的随机张量
print(tensor1)

tensor([[0.069872, 0.807757],
        [0.396409, 0.241140],
        [0.426574, 0.370559]])


In [21]:
ndarray1 = tensor1.numpy() # 将张量转换为ndarray
print(ndarray1)

[[0.069872 0.807757]
 [0.396409 0.24114 ]
 [0.426574 0.370559]]


In [28]:
# 验证数据内存共享
tensor1[:, 0] = 5 # 将张量的第一列全部赋值为5 ":" 表示所有行， "1:" 表示从第二行开始的所有行 "0:2" 表示第一行和第二行，可以简化成":2"
print(tensor1)
print(ndarray1) # ndarray 也会发生变化
ndarray1[:2, 1] = 10 # 将ndarray的前两行的第二列全部赋值为10
print(tensor1)
print(ndarray1) ## 张量也会发生变化

tensor([[ 5.000000, 10.000000],
        [ 5.000000, 10.000000],
        [ 5.000000,  0.370559]])
[[ 5.       10.      ]
 [ 5.       10.      ]
 [ 5.        0.370559]]
tensor([[ 5.000000, 10.000000],
        [ 5.000000, 10.000000],
        [ 5.000000,  0.370559]])
[[ 5.       10.      ]
 [ 5.       10.      ]
 [ 5.        0.370559]]


In [29]:
# 避免内存共享
ndarray2 = tensor1.numpy().copy() # 将张量转换为ndarray，并复制一份数据，避免内存共享
tensor1[:, 1] = 100 # 将张量的第二列全部赋值为100
print(tensor1)
print(ndarray2) # ndarray 不会发生变化

tensor([[  5., 100.],
        [  5., 100.],
        [  5., 100.]])
[[ 5.       10.      ]
 [ 5.       10.      ]
 [ 5.        0.370559]]


In [31]:
# 2. ndarray 转 Tensor
ndarray1 = np.random.randn(3, 2) # 创建一个3行2列的随机ndarray
print(ndarray1)

[[ 1.307165 -1.04182 ]
 [-1.030561  1.135612]
 [-0.849262 -2.233259]]


In [33]:
tensor1 = torch.from_numpy(ndarray1) # 将ndarray转换为张量
print(tensor1)

tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [-0.849262, -2.233259]], dtype=torch.float64)


In [34]:
tensor1[2, 1] = 5 # 将张量的第三行第二列赋值为5
print(tensor1)
print(ndarray1) # ndarray 也会发生变化

tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [-0.849262,  5.000000]], dtype=torch.float64)
[[ 1.307165 -1.04182 ]
 [-1.030561  1.135612]
 [-0.849262  5.      ]]


In [35]:
# 避免内存共享
tensor2 = torch.from_numpy(ndarray1).clone() # 将ndarray转换为张量，并复制一份数据，避免内存共享
print(tensor2)

tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [-0.849262,  5.000000]], dtype=torch.float64)


In [36]:
tensor1[2, 0] = 1.25
print(tensor1)
print(ndarray1) # ndarry 也会发生变化
print(tensor2) # 张量不会发生变化

tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [ 1.250000,  5.000000]], dtype=torch.float64)
[[ 1.307165 -1.04182 ]
 [-1.030561  1.135612]
 [ 1.25      5.      ]]
tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [-0.849262,  5.000000]], dtype=torch.float64)


In [38]:
tensor2[2, 1] = 5.2
print(tensor2)
print(ndarray1)

tensor([[ 1.307165, -1.041820],
        [-1.030561,  1.135612],
        [-0.849262,  5.200000]], dtype=torch.float64)
[[ 1.307165 -1.04182 ]
 [-1.030561  1.135612]
 [ 1.25      5.      ]]


In [40]:
# 3. 用tensor 方法直接基于内容创建张量
ndarray1 = np.random.randn(3, 2)
print(ndarray1)

[[-1.199274  1.003728]
 [-0.430345 -2.57261 ]
 [-0.546104 -0.878119]]


In [41]:
tensor1 = torch.tensor(ndarray1) # 将ndarray转换为张量，不会共享内存
print(tensor1)

tensor([[-1.199274,  1.003728],
        [-0.430345, -2.572610],
        [-0.546104, -0.878119]], dtype=torch.float64)


In [43]:
tensor1[2, 0] = 1.25
print(tensor1)
print(ndarray1) # ndarray 不会发生变化

tensor([[-1.199274,  1.003728],
        [-0.430345, -2.572610],
        [ 1.250000, -0.878119]], dtype=torch.float64)
[[-1.199274  1.003728]
 [-0.430345 -2.57261 ]
 [-0.546104 -0.878119]]
