In [1]:
import torch

In [8]:
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1)

tensor([[6, 4, 5],
        [1, 5, 9]])


## 1. 张量基本运算

In [11]:
# 使用运算符号 (不改变原张量)
print(tensor1 + 10) # tensor1 的每个元素都加上10
print(tensor1) # tensor1 不会发生变化

tensor([[16, 14, 15],
        [11, 15, 19]])
tensor([[6, 4, 5],
        [1, 5, 9]])


In [12]:
# 调用 add 方法 （不改变原张量）
print(tensor1.add(20)) # tensor1 的每个元素都加上20
print(tensor1) # tensor1 不会发生变化

tensor([[26, 24, 25],
        [21, 25, 29]])
tensor([[6, 4, 5],
        [1, 5, 9]])


In [14]:
# 使用 add_ 方法 （改变原张量）
print(tensor1.add_(30)) # tensor1 的每个元素都加上30
print(tensor1) # tensor1 会发生变化

tensor([[36, 34, 35],
        [31, 35, 39]])
tensor([[36, 34, 35],
        [31, 35, 39]])


In [16]:
tensor2 = torch.tensor([1, 2, 3])
print(tensor2.exp()) # 已 e 为底数求幂(指数) e^x

tensor([ 2.7183,  7.3891, 20.0855])


In [17]:
print(tensor2.log()) # 已 e 为底数求对数 log_e(x)

tensor([0.0000, 0.6931, 1.0986])
