In [1]:
import torch

In [8]:
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1)

tensor([[6, 4, 5],
        [1, 5, 9]])


## 1. 张量基本运算

In [11]:
# 使用运算符号 (不改变原张量)
print(tensor1 + 10) # tensor1 的每个元素都加上10
print(tensor1) # tensor1 不会发生变化

tensor([[16, 14, 15],
        [11, 15, 19]])
tensor([[6, 4, 5],
        [1, 5, 9]])


In [12]:
# 调用 add 方法 （不改变原张量）
print(tensor1.add(20)) # tensor1 的每个元素都加上20
print(tensor1) # tensor1 不会发生变化

tensor([[26, 24, 25],
        [21, 25, 29]])
tensor([[6, 4, 5],
        [1, 5, 9]])


In [14]:
# 使用 add_ 方法 （改变原张量）
print(tensor1.add_(30)) # tensor1 的每个元素都加上30
print(tensor1) # tensor1 会发生变化

tensor([[36, 34, 35],
        [31, 35, 39]])
tensor([[36, 34, 35],
        [31, 35, 39]])


In [16]:
tensor2 = torch.tensor([1, 2, 3])
print(tensor2.exp()) # 已 e 为底数求幂(指数) e^x

tensor([ 2.7183,  7.3891, 20.0855])


In [18]:
print(tensor2.log()) # 已 e 为底数求对数 log_e(x)

tensor([0.0000, 0.6931, 1.0986])


## 2. 元素级运算（张量与张量的运算）

In [19]:
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
tensor2 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1)
print(tensor2)

tensor([[6, 8, 9],
        [1, 6, 4]])
tensor([[4, 9, 6],
        [6, 9, 6]])


In [20]:
print(tensor1 + tensor2) # 张量对应元素相加

tensor([[10, 17, 15],
        [ 7, 15, 10]])


In [25]:
tensor3 = torch.randint(low=1, high=10, size=(1, 3))
print(tensor3)

tensor([[6, 7, 1]])


In [26]:
print(tensor1 + tensor3) # 张量对应元素相加，广播机制

tensor([[12, 15, 10],
        [ 7, 13,  5]])


In [27]:
print(tensor1 * tensor2) # 张量对应元素相乘-哈达玛积（元素级乘法）

tensor([[24, 72, 54],
        [ 6, 54, 24]])


## 3. 张量的矩阵乘法

In [32]:
tensor1 = torch.randint(low=1, high=10, size=(2, 3))
tensor2 = torch.randint(low=1, high=10, size=(2, 3))
print(tensor1)
print(tensor2.T)

tensor([[3, 8, 4],
        [5, 7, 3]])
tensor([[5, 8],
        [3, 9],
        [8, 9]])


In [33]:
print(tensor1 @ tensor2.T) #

tensor([[ 71, 132],
        [ 70, 130]])


In [35]:
print(tensor1.mm(tensor2.T)) # mm: matrix multiplication 矩阵乘法，只能用于二维张量

tensor([[ 71, 132],
        [ 70, 130]])


In [36]:
print(tensor1.matmul(tensor2.T)) # matmul: matrix multiplication 矩阵乘法，可以用于二维张量和高维张量

tensor([[ 71, 132],
        [ 70, 130]])


In [39]:
tensor1 = torch.randint(1, 10, (2, 3, 4)) # 2个3行4列的矩阵
tensor2 = torch.randint(1, 10, (2, 4, 2))
print(tensor1)
print(tensor2)


tensor([[[9, 2, 4, 6],
         [9, 8, 2, 1],
         [7, 6, 4, 4]],

        [[7, 4, 2, 9],
         [3, 2, 9, 8],
         [2, 4, 3, 7]]])
tensor([[[8, 2],
         [4, 9],
         [3, 4],
         [1, 1]],

        [[2, 4],
         [7, 3],
         [6, 9],
         [4, 8]]])


In [40]:
print(tensor1 @ tensor2) # 得到一个(2, 3, 2) 的张量

tensor([[[ 98,  58],
         [111,  99],
         [ 96,  88]],

        [[ 90, 130],
         [106, 163],
         [ 78, 103]]])


In [41]:
print(tensor1.matmul(tensor2)) # 得到一个(2, 3, 2) 的张量

tensor([[[ 98,  58],
         [111,  99],
         [ 96,  88]],

        [[ 90, 130],
         [106, 163],
         [ 78, 103]]])
