In [13]:
import torch

In [14]:
tensor1 = torch.randint(1, 10, (2, 3, 4)) # 2个3行4列的矩阵
print(tensor1)

tensor([[[1, 6, 8, 2],
         [3, 9, 9, 2],
         [5, 5, 9, 2]],

        [[3, 1, 2, 1],
         [8, 8, 8, 5],
         [6, 2, 2, 2]]])


In [15]:
# 1. sum 求和
print(tensor1.sum()) # 求所有元素的和

tensor(109)


In [23]:
print(tensor1.sum(dim=0)) # dim=0: 表示2个矩阵对应元素相加，得到一个3行4列的矩阵 dim=1: 表示每个矩阵的每列元素相加，每个矩阵变成1维向量，最终得到一个2行4列的矩阵 dim=2: 表示每个矩阵的每行元素相加，每个矩阵变成1维向量，最终得到一个2行3列的矩阵

tensor([[ 4,  7, 10,  3],
        [11, 17, 17,  7],
        [11,  7, 11,  4]])


In [27]:
print(torch.sum(tensor1, dim=1)) # 等价于 tensor1.sum(dim=1)

tensor([[ 9., 20., 26.,  6.],
        [17., 11., 12.,  8.]])


In [32]:
# 2. mean 求平均值
tensor1 = tensor1.float()
print(tensor1.mean()) # 求所有元素的平均值
print(tensor1.mean(dim=0)) # dim=0: 表示2个矩阵对应元素求平均值，得到一个3行4列的矩阵
print(tensor1.mean(dim=1)) # dim=1: 表示每个矩阵的每列元素求平均值，每个矩阵变成1维向量，最终得到一个2行4列的矩阵
print(tensor1.mean(dim=2)) # dim=2: 表示每个矩阵的每行元素求平均值，每个矩阵变成1维向量，最终得到一个2行3列的矩阵

tensor(4.5417)
tensor([[2.0000, 3.5000, 5.0000, 1.5000],
        [5.5000, 8.5000, 8.5000, 3.5000],
        [5.5000, 3.5000, 5.5000, 2.0000]])
tensor([[3.0000, 6.6667, 8.6667, 2.0000],
        [5.6667, 3.6667, 4.0000, 2.6667]])
tensor([[4.2500, 5.7500, 5.2500],
        [1.7500, 7.2500, 3.0000]])


In [39]:
# 3. max / min 求最大值/最小值
print(tensor1.max()) # 求所有元素的最大值
print(tensor1.max(dim=0)) # dim=0: 表示2个矩阵对应元素求最大值，得到一个3行4列的矩阵
print(tensor1.max(dim=1)) # dim=1: 表示每个矩阵的每列元素求最大值，每个矩阵变成1维向量，最终得到一个2行4列的矩阵
print(tensor1.max(dim=2)) # dim=2: 表示每个矩阵的每行元素求最大值，每个矩阵变成1维向量，最终得到一个2行3列的矩阵


tensor(9.)
torch.return_types.max(
values=tensor([[3., 6., 8., 2.],
        [8., 9., 9., 5.],
        [6., 5., 9., 2.]]),
indices=tensor([[1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 0]]))
torch.return_types.max(
values=tensor([[5., 9., 9., 2.],
        [8., 8., 8., 5.]]),
indices=tensor([[2, 1, 1, 0],
        [1, 1, 1, 1]]))
torch.return_types.max(
values=tensor([[8., 9., 9.],
        [3., 8., 6.]]),
indices=tensor([[2, 1, 2],
        [0, 0, 0]]))


In [42]:
print(tensor1.argmax(dim=0)) # dim=0: 表示2个矩阵对应元素求最大值的索引
print(tensor1.argmax(dim=1)) # dim=1: 表示每个矩阵的每列元素求最大值的索引
print(tensor1.argmax(dim=2)) # dim=2: 表示每个矩阵的每行元素求最大值的索引

tensor([[1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 0, 0]])
tensor([[2, 1, 1, 0],
        [1, 1, 1, 1]])
tensor([[2, 1, 2],
        [0, 0, 0]])


In [43]:
# 4. var, std 求方差/标准差
print(tensor1.std(dim=1)) # 标准差

tensor([[2.0000, 2.0817, 0.5774, 0.0000],
        [2.5166, 3.7859, 3.4641, 2.0817]])


In [45]:
print(tensor1.var(dim=1)) # 方差

tensor([[ 4.0000,  4.3333,  0.3333,  0.0000],
        [ 6.3333, 14.3333, 12.0000,  4.3333]])


In [57]:
# 5. unique 去重
print(tensor1.unique())

tensor([1., 2., 3., 5., 6., 8., 9.])


In [60]:
# 6. sort 排序
print(tensor1.sort()) # 默认dim=-1, 表示对最后一个维度每一个元素进行排序，等于对每一行内部排序
print(tensor1.sort(dim=1)) # dim=1, 表示对每个矩阵的每列元素进行排序

torch.return_types.sort(
values=tensor([[[1., 2., 6., 8.],
         [2., 3., 9., 9.],
         [2., 5., 5., 9.]],

        [[1., 1., 2., 3.],
         [5., 8., 8., 8.],
         [2., 2., 2., 6.]]]),
indices=tensor([[[0, 3, 1, 2],
         [3, 0, 1, 2],
         [3, 0, 1, 2]],

        [[1, 3, 2, 0],
         [3, 0, 1, 2],
         [1, 2, 3, 0]]]))
torch.return_types.sort(
values=tensor([[[1., 5., 8., 2.],
         [3., 6., 9., 2.],
         [5., 9., 9., 2.]],

        [[3., 1., 2., 1.],
         [6., 2., 2., 2.],
         [8., 8., 8., 5.]]]),
indices=tensor([[[0, 2, 0, 0],
         [1, 0, 1, 1],
         [2, 1, 2, 2]],

        [[0, 0, 0, 0],
         [2, 2, 2, 2],
         [1, 1, 1, 1]]]))
