In [1]:
import torch

In [2]:
tensor1 = torch.randint(1, 10, (3, 5, 4)) # 创建一个3*5*4的张量，元素为1-9之间的随机整数
print(tensor1)

tensor([[[7, 8, 5, 4],
         [4, 8, 2, 5],
         [1, 5, 4, 5],
         [1, 1, 1, 3],
         [1, 5, 1, 3]],

        [[1, 5, 2, 5],
         [1, 6, 3, 9],
         [3, 6, 4, 1],
         [2, 5, 4, 1],
         [4, 7, 1, 8]],

        [[1, 4, 5, 7],
         [4, 8, 3, 3],
         [2, 6, 8, 4],
         [2, 8, 9, 9],
         [8, 8, 3, 2]]])


## 简单索引

In [4]:
print(tensor1[0, 1, 2]) # 取0维第0个，1维第1个，2维第2个对应的元素

tensor(2)


In [7]:
print(tensor1[0, 0]) # 取0维第0个，1维第0个，2维所有元素
print(tensor1[0, 0, :]) # 取0维第0个，1维第0个，2维所有元素

tensor([7, 8, 5, 4])
tensor([7, 8, 5, 4])


In [9]:
print(tensor1[1]) # 取0维第1个所有元素

tensor([[1, 5, 2, 5],
        [1, 6, 3, 9],
        [3, 6, 4, 1],
        [2, 5, 4, 1],
        [4, 7, 1, 8]])


In [11]:
print(tensor1[1, :, 2]) # 取0维第1个，1维所有，2维第2个对应的所有元素

tensor([2, 3, 4, 4, 1])


In [12]:
print(tensor1[:, 1]) # 取0维第0个、第1个、第2个，1维第1个所有的元素

tensor([[4, 8, 2, 5],
        [1, 6, 3, 9],
        [4, 8, 3, 3]])


In [13]:
print(tensor1[:, :, 1]) # 取0维第0个-第2个，1维第0-第4个，2维第1个所有元素

tensor([[8, 8, 5, 1, 5],
        [5, 6, 6, 5, 7],
        [4, 8, 6, 8, 8]])


## 范围索引（切片索引）

In [17]:
print(tensor1[1:]) # 取0维第1个后面的所有元素 与 tensor1[1, :] 不同，tensor1[1, :] 表示取0维第1个所有的元素

tensor([[[1, 5, 2, 5],
         [1, 6, 3, 9],
         [3, 6, 4, 1],
         [2, 5, 4, 1],
         [4, 7, 1, 8]],

        [[1, 4, 5, 7],
         [4, 8, 3, 3],
         [2, 6, 8, 4],
         [2, 8, 9, 9],
         [8, 8, 3, 2]]])


In [19]:
print(tensor1[:, 1:4, 0:3]) # 取0维第0个-第2个，1维第[1, 4)个，2维第[0, 3) 对应的所有元素

tensor([[[4, 8, 2],
         [1, 5, 4],
         [1, 1, 1]],

        [[1, 6, 3],
         [3, 6, 4],
         [2, 5, 4]],

        [[4, 8, 3],
         [2, 6, 8],
         [2, 8, 9]]])


In [21]:
print(tensor1[:, 1:4, 0:3:2]) #  0:3:2 表示2维取 start=0 end=3 step=2 索引对应的元素

tensor([[[4, 2],
         [1, 4],
         [1, 1]],

        [[1, 3],
         [3, 4],
         [2, 4]],

        [[4, 3],
         [2, 8],
         [2, 9]]])


In [23]:
print(tensor1[-2:-1, 1:4, 0:3:2]) # -2:-1 表示0维取index=-2（-2:-1 切片是不包含end的）index=-2 == index=1

tensor([[[1, 3],
         [3, 4],
         [2, 4]]])


## 列表索引

In [26]:
list1 = [0, 2] # 0维 第0个 和 第2个， 即0维对应的坐标
list2 = [1, 4] # 0维第0个1维第1个 0维第2个1维第4个， 即0维下1维对应的坐标 等价于：tensor1[0, 1, :] 和 tensor1[2, 4, :]
print(tensor1[list1, list2])

tensor([[4, 8, 2, 5],
        [8, 8, 3, 2]])


In [28]:
list1 = [[0], [1]] #取0维度索引维0和1
list2 = [1, 4, 3]
print(tensor1[list1, list2])

tensor([[[4, 8, 2, 5],
         [1, 5, 1, 3],
         [1, 1, 1, 3]],

        [[1, 6, 3, 9],
         [4, 7, 1, 8],
         [2, 5, 4, 1]]])


## 布尔索引

In [30]:
# 1. 取所有大于5的元素
mask = tensor1 > 5
print(mask)

tensor([[[ True,  True, False, False],
         [False,  True, False, False],
         [False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False,  True, False,  True],
         [False,  True, False, False],
         [False, False, False, False],
         [False,  True, False,  True]],

        [[False, False, False,  True],
         [False,  True, False, False],
         [False,  True,  True, False],
         [False,  True,  True,  True],
         [ True,  True, False, False]]])


In [31]:
print(tensor1[mask])

tensor([7, 8, 8, 6, 9, 6, 7, 8, 7, 8, 6, 8, 8, 9, 9, 8, 8])


In [33]:
# 2. 选取符合条件的行：首元素大于5
mask = tensor1[:, :, 0] > 5
print(mask)

tensor([[ True, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False,  True]])


In [34]:
print(tensor1[mask])

tensor([[7, 8, 5, 4],
        [8, 8, 3, 2]])


In [35]:
# 3. 选取符合条件的列：首元素大于5
mask = tensor1[:, 0, :] > 5
print(mask)

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False, False, False,  True]])


In [36]:
print(tensor1[mask]) # 会报错，因为形状不一致

IndexError: The shape of the mask [3, 4] at index 1 does not match the shape of the indexed tensor [3, 5, 4] at index 1

In [38]:
tensor2 = tensor1.mT # 矩阵维度转置
print(tensor2)
print(tensor2.shape)

tensor([[[7, 4, 1, 1, 1],
         [8, 8, 5, 1, 5],
         [5, 2, 4, 1, 1],
         [4, 5, 5, 3, 3]],

        [[1, 1, 3, 2, 4],
         [5, 6, 6, 5, 7],
         [2, 3, 4, 4, 1],
         [5, 9, 1, 1, 8]],

        [[1, 4, 2, 2, 8],
         [4, 8, 6, 8, 8],
         [5, 3, 8, 9, 3],
         [7, 3, 4, 9, 2]]])
torch.Size([3, 4, 5])


In [46]:
mask = tensor2[:, :, 0] > 5
print(mask)

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False, False, False,  True]])


In [48]:
print(tensor2[mask].mT)

tensor([[7, 8, 7],
        [4, 8, 3],
        [1, 5, 4],
        [1, 1, 9],
        [1, 5, 2]])


In [54]:
# 4. 选取符合条件的矩阵：(1, 2)元素大于2
mask = tensor1[:, 1, 2] > 2
print(mask)

tensor([False,  True,  True])


In [55]:
print(tensor1[mask])

tensor([[[1, 5, 2, 5],
         [1, 6, 3, 9],
         [3, 6, 4, 1],
         [2, 5, 4, 1],
         [4, 7, 1, 8]],

        [[1, 4, 5, 7],
         [4, 8, 3, 3],
         [2, 6, 8, 4],
         [2, 8, 9, 9],
         [8, 8, 3, 2]]])
