In [74]:
import torch

In [75]:
tensor1 = torch.randint(1, 10, (3, 2, 6))
print(tensor1)

tensor([[[2, 6, 2, 6, 4, 6],
         [4, 1, 1, 4, 8, 4]],

        [[6, 1, 8, 3, 2, 2],
         [1, 6, 3, 2, 4, 3]],

        [[7, 8, 6, 3, 6, 7],
         [9, 9, 7, 4, 3, 4]]])


## 变换维度

In [76]:
# 1. .T 转置所有维度 0维和2维的交换
print(tensor1.T) # (3, 2, 6) -> (6, 2, 3)

tensor([[[2, 6, 7],
         [4, 1, 9]],

        [[6, 1, 8],
         [1, 6, 9]],

        [[2, 8, 6],
         [1, 3, 7]],

        [[6, 3, 3],
         [4, 2, 4]],

        [[4, 2, 6],
         [8, 4, 3]],

        [[6, 2, 7],
         [4, 3, 4]]])


In [77]:
# 2. .mT 矩阵转换
print(tensor1.mT)

tensor([[[2, 4],
         [6, 1],
         [2, 1],
         [6, 4],
         [4, 8],
         [6, 4]],

        [[6, 1],
         [1, 6],
         [8, 3],
         [3, 2],
         [2, 4],
         [2, 3]],

        [[7, 9],
         [8, 9],
         [6, 7],
         [3, 4],
         [6, 3],
         [7, 4]]])


In [78]:
# 3. transpose 交换两个维度
print(tensor1.transpose(0, 2)) # (3, 2, 6) -> (6, 2, 3) 0维和2维交换

tensor([[[2, 6, 7],
         [4, 1, 9]],

        [[6, 1, 8],
         [1, 6, 9]],

        [[2, 8, 6],
         [1, 3, 7]],

        [[6, 3, 3],
         [4, 2, 4]],

        [[4, 2, 6],
         [8, 4, 3]],

        [[6, 2, 7],
         [4, 3, 4]]])


In [79]:
print(tensor1.transpose(-1, -2)) # (3, 2, 6) -> (3, 6, 2) 1维和2维交换

tensor([[[2, 4],
         [6, 1],
         [2, 1],
         [6, 4],
         [4, 8],
         [6, 4]],

        [[6, 1],
         [1, 6],
         [8, 3],
         [3, 2],
         [2, 4],
         [2, 3]],

        [[7, 9],
         [8, 9],
         [6, 7],
         [3, 4],
         [6, 3],
         [7, 4]]])


In [80]:
# 4. permute 重新排列所有维度
print(tensor1.permute(2, 0, 1)) # (3, 2, 6) -> (6, 3, 2) 0维变成1维，1维变成2维，2维变成0维

tensor([[[2, 4],
         [6, 1],
         [7, 9]],

        [[6, 1],
         [1, 6],
         [8, 9]],

        [[2, 1],
         [8, 3],
         [6, 7]],

        [[6, 4],
         [3, 2],
         [3, 4]],

        [[4, 8],
         [2, 4],
         [6, 3]],

        [[6, 4],
         [2, 3],
         [7, 4]]])


## 调整形状

In [81]:
# 1. reshape 调整形状
print(tensor1.shape)
print(tensor1.reshape(4, 3, 3)) # (3, 2, 6) -> (4, 3, 3) 重新调整形状，元素总数不变

torch.Size([3, 2, 6])
tensor([[[2, 6, 2],
         [6, 4, 6],
         [4, 1, 1]],

        [[4, 8, 4],
         [6, 1, 8],
         [3, 2, 2]],

        [[1, 6, 3],
         [2, 4, 3],
         [7, 8, 6]],

        [[3, 6, 7],
         [9, 9, 7],
         [4, 3, 4]]])


In [82]:
print(tensor1.reshape(4, 9)) # (3, 2, 6) -> (4, 9) 重新调整形状，元素总数不变

tensor([[2, 6, 2, 6, 4, 6, 4, 1, 1],
        [4, 8, 4, 6, 1, 8, 3, 2, 2],
        [1, 6, 3, 2, 4, 3, 7, 8, 6],
        [3, 6, 7, 9, 9, 7, 4, 3, 4]])


In [83]:
print(tensor1.reshape(6, -1)) # (3, 2, 6) -> (6, 6) 重新调整形状，元素总数不变 -1表示自动计算该维度的大小

tensor([[2, 6, 2, 6, 4, 6],
        [4, 1, 1, 4, 8, 4],
        [6, 1, 8, 3, 2, 2],
        [1, 6, 3, 2, 4, 3],
        [7, 8, 6, 3, 6, 7],
        [9, 9, 7, 4, 3, 4]])


In [84]:
print(tensor1.reshape(-1)) # (3, 2, 6) -> (36,) 重新调整形状，元素总数不变 变换成一个行向量

tensor([2, 6, 2, 6, 4, 6, 4, 1, 1, 4, 8, 4, 6, 1, 8, 3, 2, 2, 1, 6, 3, 2, 4, 3,
        7, 8, 6, 3, 6, 7, 9, 9, 7, 4, 3, 4])


In [85]:
print(tensor1.reshape(1, -1)) # (3, 2, 6) -> (1, 36) 重新调整形状，元素总数不变 变换成一个1x36的二维矩阵

tensor([[2, 6, 2, 6, 4, 6, 4, 1, 1, 4, 8, 4, 6, 1, 8, 3, 2, 2, 1, 6, 3, 2, 4, 3,
         7, 8, 6, 3, 6, 7, 9, 9, 7, 4, 3, 4]])


In [86]:
print(tensor1.reshape(-1, 1)) # (3, 2, 6) -> (36, 1) 重新调整形状，元素总数不变 变换成一个36x1的二维矩阵

tensor([[2],
        [6],
        [2],
        [6],
        [4],
        [6],
        [4],
        [1],
        [1],
        [4],
        [8],
        [4],
        [6],
        [1],
        [8],
        [3],
        [2],
        [2],
        [1],
        [6],
        [3],
        [2],
        [4],
        [3],
        [7],
        [8],
        [6],
        [3],
        [6],
        [7],
        [9],
        [9],
        [7],
        [4],
        [3],
        [4]])


In [87]:
print(tensor1.reshape(2, 3, 3, 2)) # (3, 2, 6) -> (2, 3, 3, 2) 重新调整形状，元素总数不变

tensor([[[[2, 6],
          [2, 6],
          [4, 6]],

         [[4, 1],
          [1, 4],
          [8, 4]],

         [[6, 1],
          [8, 3],
          [2, 2]]],


        [[[1, 6],
          [3, 2],
          [4, 3]],

         [[7, 8],
          [6, 3],
          [6, 7]],

         [[9, 9],
          [7, 4],
          [3, 4]]]])


In [88]:
# 2. view 调整形状 需要内存连续。共享内存
print(tensor1.shape)

torch.Size([3, 2, 6])


In [89]:
print(tensor1.view(4, -1))

tensor([[2, 6, 2, 6, 4, 6, 4, 1, 1],
        [4, 8, 4, 6, 1, 8, 3, 2, 2],
        [1, 6, 3, 2, 4, 3, 7, 8, 6],
        [3, 6, 7, 9, 9, 7, 4, 3, 4]])


In [90]:
print(tensor1.is_contiguous()) # 判断是否内存连续

True


In [91]:
tensor1 = tensor1.permute(2, 0 ,1) # 维度变换，会导致内存不连续
print(tensor1.shape)

torch.Size([6, 3, 2])


In [92]:
print(tensor1.is_contiguous()) # 判断是否内存连续

False


In [93]:
print(tensor1.view(4, -1)) # 会报错，因为内存不连续

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [94]:
print(tensor1.contiguous().view(4, -1)) # 先调用 contiguous() 方法，使内存连续，再调用 view() 方法调整形状

tensor([[2, 4, 6, 1, 7, 9, 6, 1, 1],
        [6, 8, 9, 2, 1, 8, 3, 6, 7],
        [6, 4, 3, 2, 3, 4, 4, 8, 2],
        [4, 6, 3, 6, 4, 2, 3, 7, 4]])


## 增删维度

In [95]:
tensor1 = torch.randint(1, 10, (3, 2, 6))
print(tensor1)

tensor([[[6, 8, 5, 8, 8, 6],
         [8, 6, 3, 4, 5, 2]],

        [[5, 4, 8, 2, 3, 5],
         [4, 4, 4, 4, 8, 2]],

        [[2, 8, 4, 6, 5, 8],
         [1, 2, 5, 8, 7, 7]]])


In [96]:
# 1. 增加维度
print(tensor1.reshape(1, 3, 2, 6)) # (6, 3, 2) -> (1, 6, 3, 2) 增加一个维度

tensor([[[[6, 8, 5, 8, 8, 6],
          [8, 6, 3, 4, 5, 2]],

         [[5, 4, 8, 2, 3, 5],
          [4, 4, 4, 4, 8, 2]],

         [[2, 8, 4, 6, 5, 8],
          [1, 2, 5, 8, 7, 7]]]])


In [97]:
print(tensor1.reshape(3, 1, 2, 6))

tensor([[[[6, 8, 5, 8, 8, 6],
          [8, 6, 3, 4, 5, 2]]],


        [[[5, 4, 8, 2, 3, 5],
          [4, 4, 4, 4, 8, 2]]],


        [[[2, 8, 4, 6, 5, 8],
          [1, 2, 5, 8, 7, 7]]]])


In [98]:
print(tensor1.unsqueeze(0)) # 0维增加一个维度 (3, 2, 6) -> (1, 3, 2, 6)

tensor([[[[6, 8, 5, 8, 8, 6],
          [8, 6, 3, 4, 5, 2]],

         [[5, 4, 8, 2, 3, 5],
          [4, 4, 4, 4, 8, 2]],

         [[2, 8, 4, 6, 5, 8],
          [1, 2, 5, 8, 7, 7]]]])


In [99]:
print(tensor1.unsqueeze(1)) # 1维增加一个维度 (3, 2, 6) -> (3, 1, 2, 6)
#

tensor([[[[6, 8, 5, 8, 8, 6],
          [8, 6, 3, 4, 5, 2]]],


        [[[5, 4, 8, 2, 3, 5],
          [4, 4, 4, 4, 8, 2]]],


        [[[2, 8, 4, 6, 5, 8],
          [1, 2, 5, 8, 7, 7]]]])


In [100]:
print(tensor1.unsqueeze(dim=3)) # 3维增加一个维度 (3, 2, 6) -> (3, 2, 6, 1)

tensor([[[[6],
          [8],
          [5],
          [8],
          [8],
          [6]],

         [[8],
          [6],
          [3],
          [4],
          [5],
          [2]]],


        [[[5],
          [4],
          [8],
          [2],
          [3],
          [5]],

         [[4],
          [4],
          [4],
          [4],
          [8],
          [2]]],


        [[[2],
          [8],
          [4],
          [6],
          [5],
          [8]],

         [[1],
          [2],
          [5],
          [8],
          [7],
          [7]]]])


In [105]:
tensor2 = tensor1.unsqueeze(0) # 0维增加一个维度 (3, 2, 6) -> (1, 3, 2, 6)
print(tensor2)

tensor([[[[6, 8, 5, 8, 8, 6],
          [8, 6, 3, 4, 5, 2]],

         [[5, 4, 8, 2, 3, 5],
          [4, 4, 4, 4, 8, 2]],

         [[2, 8, 4, 6, 5, 8],
          [1, 2, 5, 8, 7, 7]]]])


In [108]:
# 2. 删除维度(降维)
print(tensor2.squeeze(0).shape) # 删除0维 (1, 3, 2, 6) -> (3, 2, 6)
print(tensor2.squeeze().shape) # 删除所有为1的维度 (1, 3, 2, 6) -> (3, 2, 6)

torch.Size([3, 2, 6])
torch.Size([3, 2, 6])


## 张量拼接

In [117]:
# 1. cat 指定维度拼接 要求只有1个维度不同，其他维度相同
tensor1 = torch.randint(1, 10, (3, 2, 6))
tensor2 = torch.randint(1, 10, (3, 3, 6))
print(tensor1)
print(tensor2)

tensor([[[7, 4, 4, 3, 9, 4],
         [6, 1, 4, 8, 3, 1]],

        [[9, 8, 3, 2, 7, 1],
         [5, 3, 1, 9, 3, 6]],

        [[5, 5, 3, 2, 6, 5],
         [3, 3, 8, 2, 7, 2]]])
tensor([[[2, 2, 2, 2, 7, 4],
         [2, 7, 7, 7, 7, 1],
         [5, 8, 8, 6, 5, 2]],

        [[4, 4, 2, 2, 3, 1],
         [4, 1, 7, 4, 3, 1],
         [7, 7, 3, 9, 6, 5]],

        [[3, 1, 2, 6, 4, 9],
         [3, 7, 5, 2, 4, 8],
         [4, 3, 7, 5, 8, 4]]])


In [118]:
tensor3 = torch.cat([tensor1, tensor2], dim=1) # (3, 2, 6) + (3, 3, 6) -> (3, 5, 6) 指定维度拼接
print(tensor3)
print(tensor3.shape)

tensor([[[7, 4, 4, 3, 9, 4],
         [6, 1, 4, 8, 3, 1],
         [2, 2, 2, 2, 7, 4],
         [2, 7, 7, 7, 7, 1],
         [5, 8, 8, 6, 5, 2]],

        [[9, 8, 3, 2, 7, 1],
         [5, 3, 1, 9, 3, 6],
         [4, 4, 2, 2, 3, 1],
         [4, 1, 7, 4, 3, 1],
         [7, 7, 3, 9, 6, 5]],

        [[5, 5, 3, 2, 6, 5],
         [3, 3, 8, 2, 7, 2],
         [3, 1, 2, 6, 4, 9],
         [3, 7, 5, 2, 4, 8],
         [4, 3, 7, 5, 8, 4]]])
torch.Size([3, 5, 6])


In [119]:
# 2. stack 堆叠拼接 要求所有维度相同（形状相同）
tensor1 = torch.randint(1, 10, (4, 3, 6))
tensor2 = torch.randint(1, 10, (4, 3, 6))
print(tensor1)
print(tensor2)

tensor([[[7, 8, 1, 2, 6, 8],
         [4, 8, 5, 4, 4, 8],
         [4, 9, 1, 5, 3, 5]],

        [[6, 9, 6, 5, 4, 4],
         [5, 1, 8, 1, 8, 4],
         [9, 9, 2, 9, 7, 6]],

        [[4, 3, 8, 6, 3, 6],
         [7, 6, 6, 9, 3, 7],
         [5, 5, 3, 3, 8, 8]],

        [[5, 2, 2, 9, 8, 2],
         [6, 6, 7, 2, 3, 8],
         [7, 9, 7, 2, 6, 4]]])
tensor([[[2, 9, 6, 5, 5, 4],
         [2, 1, 1, 8, 3, 5],
         [6, 5, 3, 7, 1, 8]],

        [[7, 3, 5, 7, 2, 9],
         [5, 2, 1, 7, 9, 6],
         [8, 7, 4, 4, 2, 1]],

        [[8, 1, 4, 9, 5, 7],
         [3, 2, 7, 7, 8, 9],
         [5, 7, 5, 2, 1, 2]],

        [[1, 1, 7, 8, 6, 1],
         [1, 7, 4, 5, 1, 8],
         [3, 5, 1, 9, 3, 7]]])


In [124]:
print(torch.stack([tensor1, tensor2]).shape) # 默认dim=0 以0维为单位进行堆叠拼接 (4, 3, 6) + (4, 3, 6) -> (2, 4, 3, 6)
print(torch.stack([tensor1, tensor2], dim=1).shape) # dim=1 以1维为单位进行堆叠拼接 (4, 3, 6) + (4, 3, 6) -> (4, 2, 3, 6)
print(torch.stack([tensor1, tensor2], dim=2).shape) # dim=2 以2维为单位进行堆叠拼接 (4, 3, 6) + (4, 3, 6) -> (4, 3, 2, 6)
print(torch.stack([tensor1, tensor2], dim=3).shape) # dim=3 张量的每一个元素进行堆叠拼接 (4, 3, 6) + (4, 3, 6) -> (4, 3, 6, 2)

torch.Size([2, 4, 3, 6])
torch.Size([4, 2, 3, 6])
torch.Size([4, 3, 2, 6])
torch.Size([4, 3, 6, 2])
