In [34]:
import torch

In [35]:
tensor1 = torch.randint(1, 10, (3, 2, 6))
print(tensor1)

tensor([[[9, 8, 5, 8, 8, 6],
         [6, 5, 2, 2, 9, 4]],

        [[9, 6, 4, 4, 6, 9],
         [6, 1, 4, 2, 4, 7]],

        [[2, 3, 6, 2, 8, 5],
         [8, 9, 2, 5, 8, 4]]])


## 变换维度

In [36]:
# 1. .T 转置所有维度 0维和2维的交换
print(tensor1.T) # (3, 2, 6) -> (6, 2, 3)

tensor([[[9, 9, 2],
         [6, 6, 8]],

        [[8, 6, 3],
         [5, 1, 9]],

        [[5, 4, 6],
         [2, 4, 2]],

        [[8, 4, 2],
         [2, 2, 5]],

        [[8, 6, 8],
         [9, 4, 8]],

        [[6, 9, 5],
         [4, 7, 4]]])


In [37]:
# 2. .mT 矩阵转换
print(tensor1.mT)

tensor([[[9, 6],
         [8, 5],
         [5, 2],
         [8, 2],
         [8, 9],
         [6, 4]],

        [[9, 6],
         [6, 1],
         [4, 4],
         [4, 2],
         [6, 4],
         [9, 7]],

        [[2, 8],
         [3, 9],
         [6, 2],
         [2, 5],
         [8, 8],
         [5, 4]]])


In [38]:
# 3. transpose 交换两个维度
print(tensor1.transpose(0, 2)) # (3, 2, 6) -> (6, 2, 3) 0维和2维交换

tensor([[[9, 9, 2],
         [6, 6, 8]],

        [[8, 6, 3],
         [5, 1, 9]],

        [[5, 4, 6],
         [2, 4, 2]],

        [[8, 4, 2],
         [2, 2, 5]],

        [[8, 6, 8],
         [9, 4, 8]],

        [[6, 9, 5],
         [4, 7, 4]]])


In [39]:
print(tensor1.transpose(-1, -2)) # (3, 2, 6) -> (3, 6, 2) 1维和2维交换

tensor([[[9, 6],
         [8, 5],
         [5, 2],
         [8, 2],
         [8, 9],
         [6, 4]],

        [[9, 6],
         [6, 1],
         [4, 4],
         [4, 2],
         [6, 4],
         [9, 7]],

        [[2, 8],
         [3, 9],
         [6, 2],
         [2, 5],
         [8, 8],
         [5, 4]]])


In [40]:
# 4. permute 重新排列所有维度
print(tensor1.permute(2, 0, 1)) # (3, 2, 6) -> (6, 3, 2) 0维变成1维，1维变成2维，2维变成0维

tensor([[[9, 6],
         [9, 6],
         [2, 8]],

        [[8, 5],
         [6, 1],
         [3, 9]],

        [[5, 2],
         [4, 4],
         [6, 2]],

        [[8, 2],
         [4, 2],
         [2, 5]],

        [[8, 9],
         [6, 4],
         [8, 8]],

        [[6, 4],
         [9, 7],
         [5, 4]]])


## 调整形状

In [41]:
# 1. reshape 调整形状
print(tensor1.shape)
print(tensor1.reshape(4, 3, 3)) # (3, 2, 6) -> (4, 3, 3) 重新调整形状，元素总数不变

torch.Size([3, 2, 6])
tensor([[[9, 8, 5],
         [8, 8, 6],
         [6, 5, 2]],

        [[2, 9, 4],
         [9, 6, 4],
         [4, 6, 9]],

        [[6, 1, 4],
         [2, 4, 7],
         [2, 3, 6]],

        [[2, 8, 5],
         [8, 9, 2],
         [5, 8, 4]]])


In [42]:
print(tensor1.reshape(4, 9)) # (3, 2, 6) -> (4, 9) 重新调整形状，元素总数不变

tensor([[9, 8, 5, 8, 8, 6, 6, 5, 2],
        [2, 9, 4, 9, 6, 4, 4, 6, 9],
        [6, 1, 4, 2, 4, 7, 2, 3, 6],
        [2, 8, 5, 8, 9, 2, 5, 8, 4]])


In [43]:
print(tensor1.reshape(6, -1)) # (3, 2, 6) -> (6, 6) 重新调整形状，元素总数不变 -1表示自动计算该维度的大小

tensor([[9, 8, 5, 8, 8, 6],
        [6, 5, 2, 2, 9, 4],
        [9, 6, 4, 4, 6, 9],
        [6, 1, 4, 2, 4, 7],
        [2, 3, 6, 2, 8, 5],
        [8, 9, 2, 5, 8, 4]])


In [44]:
print(tensor1.reshape(-1)) # (3, 2, 6) -> (36,) 重新调整形状，元素总数不变 变换成一个行向量

tensor([9, 8, 5, 8, 8, 6, 6, 5, 2, 2, 9, 4, 9, 6, 4, 4, 6, 9, 6, 1, 4, 2, 4, 7,
        2, 3, 6, 2, 8, 5, 8, 9, 2, 5, 8, 4])


In [45]:
print(tensor1.reshape(1, -1)) # (3, 2, 6) -> (1, 36) 重新调整形状，元素总数不变 变换成一个1x36的二维矩阵

tensor([[9, 8, 5, 8, 8, 6, 6, 5, 2, 2, 9, 4, 9, 6, 4, 4, 6, 9, 6, 1, 4, 2, 4, 7,
         2, 3, 6, 2, 8, 5, 8, 9, 2, 5, 8, 4]])


In [46]:
print(tensor1.reshape(-1, 1)) # (3, 2, 6) -> (36, 1) 重新调整形状，元素总数不变 变换成一个36x1的二维矩阵

tensor([[9],
        [8],
        [5],
        [8],
        [8],
        [6],
        [6],
        [5],
        [2],
        [2],
        [9],
        [4],
        [9],
        [6],
        [4],
        [4],
        [6],
        [9],
        [6],
        [1],
        [4],
        [2],
        [4],
        [7],
        [2],
        [3],
        [6],
        [2],
        [8],
        [5],
        [8],
        [9],
        [2],
        [5],
        [8],
        [4]])


In [47]:
# 2. view 调整形状 需要内存连续。共享内存
print(tensor1.shape)

torch.Size([3, 2, 6])


In [48]:
print(tensor1.view(4, -1))

tensor([[9, 8, 5, 8, 8, 6, 6, 5, 2],
        [2, 9, 4, 9, 6, 4, 4, 6, 9],
        [6, 1, 4, 2, 4, 7, 2, 3, 6],
        [2, 8, 5, 8, 9, 2, 5, 8, 4]])


In [49]:
print(tensor1.is_contiguous()) # 判断是否内存连续

True


In [50]:
tensor1 = tensor1.permute(2, 0 ,1) # 维度变换，会导致内存不连续
print(tensor1.shape)

torch.Size([6, 3, 2])


In [51]:
print(tensor1.is_contiguous()) # 判断是否内存连续

False


In [52]:
print(tensor1.view(4, -1)) # 会报错，因为内存不连续

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [53]:
print(tensor1.contiguous().view(4, -1)) # 先调用 contiguous() 方法，使内存连续，再调用 view() 方法调整形状

tensor([[9, 6, 9, 6, 2, 8, 8, 5, 6],
        [1, 3, 9, 5, 2, 4, 4, 6, 2],
        [8, 2, 4, 2, 2, 5, 8, 9, 6],
        [4, 8, 8, 6, 4, 9, 7, 5, 4]])
