In [2]:
import torch

In [3]:
tensor1 = torch.randint(1, 10, (3, 2, 6))
print(tensor1)

tensor([[[2, 6, 9, 5, 8, 9],
         [8, 3, 4, 4, 6, 5]],

        [[3, 9, 5, 4, 8, 1],
         [5, 7, 1, 4, 5, 9]],

        [[6, 8, 3, 5, 6, 4],
         [7, 1, 7, 6, 6, 9]]])


## 变换维度

In [4]:
# 1. .T 转置所有维度 0维和2维的交换
print(tensor1.T) # (3, 2, 6) -> (6, 2, 3)

tensor([[[2, 3, 6],
         [8, 5, 7]],

        [[6, 9, 8],
         [3, 7, 1]],

        [[9, 5, 3],
         [4, 1, 7]],

        [[5, 4, 5],
         [4, 4, 6]],

        [[8, 8, 6],
         [6, 5, 6]],

        [[9, 1, 4],
         [5, 9, 9]]])


/var/folders/zr/z64sgdl150v696tg363smnwh0000gn/T/ipykernel_35411/3566816899.py:2: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:4484.)
  print(tensor1.T) # (3, 2, 6) -> (6, 2, 3)


In [5]:
# 2. .mT 矩阵转换
print(tensor1.mT)

tensor([[[2, 8],
         [6, 3],
         [9, 4],
         [5, 4],
         [8, 6],
         [9, 5]],

        [[3, 5],
         [9, 7],
         [5, 1],
         [4, 4],
         [8, 5],
         [1, 9]],

        [[6, 7],
         [8, 1],
         [3, 7],
         [5, 6],
         [6, 6],
         [4, 9]]])


In [6]:
# 3. transpose 交换两个维度
print(tensor1.transpose(0, 2)) # (3, 2, 6) -> (6, 2, 3) 0维和2维交换

tensor([[[2, 3, 6],
         [8, 5, 7]],

        [[6, 9, 8],
         [3, 7, 1]],

        [[9, 5, 3],
         [4, 1, 7]],

        [[5, 4, 5],
         [4, 4, 6]],

        [[8, 8, 6],
         [6, 5, 6]],

        [[9, 1, 4],
         [5, 9, 9]]])


In [7]:
print(tensor1.transpose(-1, -2)) # (3, 2, 6) -> (3, 6, 2) 1维和2维交换

tensor([[[2, 8],
         [6, 3],
         [9, 4],
         [5, 4],
         [8, 6],
         [9, 5]],

        [[3, 5],
         [9, 7],
         [5, 1],
         [4, 4],
         [8, 5],
         [1, 9]],

        [[6, 7],
         [8, 1],
         [3, 7],
         [5, 6],
         [6, 6],
         [4, 9]]])


In [8]:
# 4. permute 重新排列所有维度
print(tensor1.permute(2, 0, 1)) # (3, 2, 6) -> (6, 3, 2) 0维变成1维，1维变成2维，2维变成0维

tensor([[[2, 8],
         [3, 5],
         [6, 7]],

        [[6, 3],
         [9, 7],
         [8, 1]],

        [[9, 4],
         [5, 1],
         [3, 7]],

        [[5, 4],
         [4, 4],
         [5, 6]],

        [[8, 6],
         [8, 5],
         [6, 6]],

        [[9, 5],
         [1, 9],
         [4, 9]]])
